version: '3'
services:
  teamspeak3-server-prd:
    build: teamspeak3-dev/.
    restart: unless-stopped
    environment:
      TS3SERVER_LICENSE: accept
    ports:
      - "9987:9987/udp"
      - 30033:30033
      - 10011:10011