{
 "title": "SMART Status",
 "description": "metrics for the S.M.A.R.T.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance)"
    }
   },
   {
    "name": "device",
    "label": "Disk",
    "query": {
     "query": "label_values(smartmon_device_info,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of unhealthy disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_healthy{device=~\".*$device\",instance=~\"$instance\"})-sum(smartmon_device_smart_healthy{device=~\".*$device\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Devices active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_active{device=~\".*$device\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Drive Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(disk) (smartmon_temperature_celsius_raw_value{instance=~\"$instance\"})",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "HDD Spin Up Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max by(disk) (smartmon_spin_up_time_value{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: {{disk}} "
    }
   ]
  },
  {
   "title": "Drive Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "smartmon_device_info{instance=~\"$instance\",device=~\".*$device\"}"
    }
   ]
  },
  {
   "title": "$device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "device",
   "targets": [
    {}
   ]
  },
  {
   "title": "Remaining lifespan",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smartmon_wear_leveling_count_raw_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SMART values",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_attr_raw_value{name=~\"reported_uncorrect|reallocated_sector_ct|command_timeout|current_pending_sector|offline_uncorrectable|power_on_hours|total_lbas_written|start_stop_count|load_cycle_count\",device=~\".*$device\",instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}