version: '3'
services:
  nginx-reverse-proxy:
    build: nginx-reverse-proxy/.
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.2

  # Monitoring Part starts here
  grafana:
    build: grafana/.
    restart: unless-stopped
    user: "root"
    environment:
       GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-piechart-panel
       GF_RENDERING_SERVER_URL: http://172.16.1.100:8081/render
       GF_RENDERING_CALLBACK_URL: http://grafana.fink.home/
       GF_LOG_FILTERS: rendering:debug
       GF_ROOT_URL: http://grafana.fink.home/
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.10
    dns:
      - 10.0.0.100

  grafana_renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      ENABLE_METRICS: "true"
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.100
    dns:
      - 10.0.0.100
    
  influxdb:
    build: influxdb/.
    restart: unless-stopped
    volumes:
    - /opt/containerd/data/monitoring/influxdb_data:/var/lib/influxdb
    - /opt/containerd/data/monitoring/influxdb_data2:/var/lib/influxdb2
    environment:
     - DOCKER_INFLUXDB_INIT_USERNAME=pmx
     - DOCKER_INFLUXDB_INIT_PASSWORD=pmx
     - DOCKER_INFLUXDB_INIT_ORG=pmx
     - DOCKER_INFLUXDB_INIT_BUCKET=proxmox
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.11

  prometheus:
    build: prometheus/.
    restart: unless-stopped
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.12

  # PiHole - Prometheus Bridge
  pihole-prometheus-exporter:
    image: 'ekofr/pihole-exporter:latest'
    environment:
    - PIHOLE_HOSTNAME=pihole0-kch.fink.home,pihole1-tg.fink.home
    - PIHOLE_API_TOKEN=491322461603f606a67431585e063eedc586908538b535384d6b0c9dbd8d5ff2,491322461603f606a67431585e063eedc586908538b535384d6b0c9dbd8d5ff2
    - PORT=9100
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.20

  # FritzBox - Prometheus Bridge
  fritzbox-prometheus-exporter-fritzbox1-tg.fink.home:
    image: kehrhardt/fritzbox_exporter:latest
    restart: unless-stopped
    environment:
      GATEWAY_URL: "http://192.168.188.1:49000" # ip of your Fritz!Box
      GATEWAY_LUAURL: "http://192.168.188.1"
      USERNAME: prometheus_bridge_user
      PASSWORD: prometheus_bridge
      LISTEN_ADDRESS: "172.16.1.21:9100"
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.21
  fritzbox-prometheus-exporter-fritzbox0-kch.fink.home:
    image: kehrhardt/fritzbox_exporter:latest
    restart: unless-stopped
    environment:
      GATEWAY_URL: "http://10.0.0.1:49000" # ip of your Fritz!Box
      GATEWAY_LUAURL: "http://10.0.0.1"
      USERNAME: prometheus_bridge_user
      PASSWORD: prometheus_bridge
      LISTEN_ADDRESS: "172.16.1.22:9100"
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.22

  # TeamSpeak - Prometheus Bridge
  #teamspeak3-promtheus-exporter:
  #  build: teamspeak3-prometheus-exporter/.
  #  restart: unless-stopped
  #  environment:
  #    TEAMSPEAK_HOST: teamspeak.fink.home
  #    TEAMSPEAK_PORT: 10011
  #    TEAMSPEAK_USERNAME: "prometheus-bridge"
  #    TEAMSPEAK_PASSWORD: "3tFmoWD9"
  #  networks:
  #    monitoring-and-ingress-prd:
  #      ipv4_address: 172.16.1.23

  #teamspeak3-prometheus-exporterv2:
  #  build: teamspeak3-prometheus-exporterv2/.
  #  restart: unless-stopped
  #  command:
  #    - "-user"
  #    - "prometheus-bridge"
  #    - "-remote"
  #    - "10.0.0.107:10011"
  #    - "-listen"
  #    - "172.16.1.23:9100"
  #  environment:
  #    SERVERQUERY_PASSWORD: "3tFmoWD9"
  #  networks:
  #    monitoring-and-ingress-prd:
  #      ipv4_address: 172.16.1.23

  # NGINX - Promehtheus Bridge
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    restart: unless-stopped
    command:
      - "-nginx.scrape-uri"
      - "http://172.16.1.2:8080/basic_status"
    networks:
      monitoring-and-ingress-prd:
        ipv4_address: 172.16.1.24

  wireguard-endpoint-localizer:
    build: wireguard-endpoint-localizer/.
    restart: unless-stopped
    networks:
      monitoring-and-ingress-prd:
      ipv4_address: 172.16.1.25

networks:
  monitoring-and-ingress-prd:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.1.0/24