{
 "title": "Wireguard Status",
 "description": "Wireguard Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peer Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "wireguard_peer_info" }
   ]
  },
  {
   "title": "Hourly Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "expr": "sum(increase(wireguard_received_bytes_total[$__interval]))",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "RX WireGuard Server",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    },
    {
     "alias": "Upload",
     "expr": "sum(increase(wireguard_sent_bytes_total[$__interval]))",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "TX WireGuard Server",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter \n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Peer Transmit Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total{job=\"WireGuard Statistics (deprecated)\"}[1m]) * on (public_key) group_left(name) wireguard_peer_info{job=\"WireGuard Statistics (deprecated)\"} * on (instance) group_left(device) wireguard_device_info{job=\"WireGuard Statistics (deprecated)\"}",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Receive Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{job=\"WireGuard Statistics (deprecated)\"}[1m]) * on (public_key) group_left(name) wireguard_peer_info{job=\"WireGuard Statistics (deprecated)\"} * on (instance) group_left(device) wireguard_device_info{job=\"WireGuard Statistics (deprecated)\"}",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Last Handshake",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-(wireguard_latest_handshake_seconds)",
     "legendFormat": "{{public_key}}"
    }
   ]
  }
 ]
}