{
 "title": "FRITZ!Box Status",
 "description": "Monitor FRITZ!Box routers using prometheus and fritzbox_exporter",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gateway",
    "query": {
     "query": "label_values(gateway_connection_status, gateway)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Active Hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(gateway_host_active{gateway=\"$gateway\"}>0)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "# WLAN Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gateway_wlan_current_connections{gateway=\"$gateway\"}",
     "legendFormat": "{{wlan}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gateway_device_modelname{gateway=\"$gateway\"}"
    }
   ]
  },
  {
   "title": "Current Downstream",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_traffic_rate{direction=\"Received\",interface=\"WAN\", gateway=\"$gateway\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ]
    }
   ]
  },
  {
   "title": "Total Downstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_traffic{direction=\"Received\",unit=\"Bytes\",interface=\"WAN\", gateway=\"$gateway\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "24h Downstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_traffic{unit=\"Bytes\",direction=\"Received\",interface=\"WAN\", gateway=\"$gateway\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(max(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_connection_status{connection=\"Physical Link\", gateway=\"$gateway\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "dslstatus" }
     ]
    }
   ]
  },
  {
   "title": "IP Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_connection_status{connection=\"IP\", gateway=\"$gateway\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "Fritzbox Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_uptime_seconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_connection_uptime_seconds{connection=\"IP\", gateway=\"$gateway\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Current Upstream",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_traffic_rate{direction=\"Sent\",interface=\"WAN\", gateway=\"$gateway\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ]
    }
   ]
  },
  {
   "title": "Total Upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_traffic{direction=\"Sent\",unit=\"Bytes\",interface=\"WAN\", gateway=\"$gateway\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "24h Upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_traffic{direction=\"Sent\",unit=\"Bytes\",interface=\"WAN\", gateway=\"$gateway\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "WAN Macaddress",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_status{connection=\"PPP\", gateway=\"$gateway\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "{{ macaddress }}",
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "Public WAN IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_status{connection=\"PPP\", gateway=\"$gateway\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "{{ externalipaddress }}",
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "Network Devices",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gateway_host_active{gateway=\"$gateway\"}"
    }
   ]
  },
  {
   "title": "Downstream Bandwith",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream",
     "expr": "gateway_connection_max_bitrate{direction=\"Down\", gateway=\"$gateway\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limit",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'receiverate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-receiverate,'downstream')"
    },
    {
     "alias": "upstream",
     "expr": "gateway_traffic_rate{direction=\"Received\", gateway=\"$gateway\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'sendrate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-sendrate,'upstream')"
    }
   ]
  },
  {
   "title": "Upstream Bandwith",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream max",
     "expr": "gateway_connection_max_bitrate{direction=\"Up\", gateway=\"$gateway\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limit",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'downstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "downstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-downstreammax,'downstream max')"
    },
    {
     "alias": "upstream max",
     "expr": "gateway_traffic_rate{direction=\"Sent\", gateway=\"$gateway\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'upstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "upstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-upstreammax,'upstream max')"
    }
   ]
  },
  {
   "title": "Hourly Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "expr": "increase(gateway_traffic{direction=\"Received\",unit=\"Bytes\", interface=\"WAN\", gateway=\"$gateway\"}[$__interval])",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "Download",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    },
    {
     "alias": "Upload",
     "expr": "increase(gateway_traffic{direction=\"Sent\",unit=\"Bytes\", interface=\"WAN\", gateway=\"$gateway\"}[$__interval])",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "legendFormat": "Upload",
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter \n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  }
 ]
}