{
 "title": "NUT Status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "generic_runtime_critical", "query": "180" }
  ]
 },
 "panels": [
  { "title": "Overview effekta_usv", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ups" },
  {
   "title": "Status",
   "type": "stat",
   "description": "UPS load percent",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(network_ups_tools_ups_status{instance=\"10.0.0.104:9199\",job=\"Effekta-USV (KCH) Status\"}) by (job)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\nnetwork_ups_tools_ups_temperature{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}) by (job)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\nnetwork_ups_tools_battery_charge{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}) by (job)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "UPS load percent",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\nnetwork_ups_tools_ups_load{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}) by (job)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_frequency{instance=\"10.0.0.104:9199\", job=\"Effekta-USV (KCH) Status\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage"
    }
   ]
  }
 ]
}