FROM teamspeak:latest
#COPY ./ts3server.sqlitedb /var/ts3server/ts3server.sqlitedb
COPY ./query_ip_blacklist.txt /var/ts3server/query_ip_blacklist.txt
COPY ./query_ip_whitelist.txt /var/ts3server/query_ip_whitelist.txt