[[servers]]
host = "freeipa2.kapra.vpn"
port = 389

use_ssl = false
start_tls = false

ssk_skip_verify = false

bind_dn = "uid=grafana,cn=sysaccounts,cn=etc,dc=kapra,dc=vpn"
bind_password = "${LDAP_BIND_PASSWORD}"

timeout = 10

#search_filter = "uid=%s,cn=users,cn=accounts,dc=kapra,dc=vpn"
search_filter = "uid=%s"

search_base_dns = ["cn=users,cn=accounts,dc=kapra,dc=vpn"]

[servers.attributes]
member_of = "memberOf"
email = "mail"

[[servers.group_mappings]]
group_dn = "cn=grafana_users,cn=groups,cn=accounts,dc=kapra,dc=vpn"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=fink.home_admins,cn=groups,cn=accounts,dc=kapra,dc=vpn"
org_role = "Admin"
grafana_admin = true
