name: Monitoring Stack Deploy
on: [push]
jobs:
  Deploy-Monitoring-And-Ingress-PRD-Stack:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: prd-docker0-kch.fink.home
          ssh_user: fink-home-docker-deploy
          ssh_key: ${{ secrets.NEW_DOCKER_SSH_KEY }}
          compose_file: ./monitoring-and-ingress-prd/docker-compose.yml
          pull: true
          build: true

  Deploy-Teamspeak3-Server-PRD-Stack:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: prd-docker0-kch.fink.home
          ssh_user: fink-home-docker-deploy
          ssh_key: ${{ secrets.NEW_DOCKER_SSH_KEY }}
          compose_file: ./teamspeak3-server-prd/docker-compose.yml
          pull: true
          build: true

  Deploy-Redmine-PRD-Stack:
    runs-on: self-hosted
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: prd-docker0-kch.fink.home
          ssh_user: fink-home-docker-deploy
          ssh_key: ${{ secrets.NEW_DOCKER_SSH_KEY }}
          compose_file: redmine-prd/docker-compose.yml
          pull: true
          build: true