global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prometheus-scraper'

scrape_configs:

  # Host Status Scrapes
  - job_name: "Node Exporter VM"
    static_configs:
      - targets: ['gameserver0-kch.fink.home:9100', 'storage0-kch.fink.home:9100', 'github-runner0-kch.fink.home:9100']
  - job_name: "Node Exporter Docker"
    static_configs:
      - targets: ['prd-docker0-kch.fink.home:9100', 'docker.fink.home:9100']
  - job_name: "Node Exporter Proxmox"
    static_configs:
      - targets: ['pbs0-kch.fink.home:9100', 'vms1.fink.home:9100', 'vms2.fink.home:9100', 'vms3.fink.home:9100']
  - job_name: "Node Exporter PiHole"
    static_configs:
      - targets: ['pihole0-kch.fink.home:9100', 'pihole1-tg.fink.home:9100']
  - job_name: "Node Exporter External"
    static_configs:
      - targets: ['offsite-backup.fink.vpn:9100']

  # Service Scrapes via external exporter source
  - job_name: 'WireGuard Statistics (deprecated)'
    static_configs:
      - targets: ['10.0.0.102:8000']

  - job_name: 'Grafana Image Rendering Service'
    static_configs:
      - targets: ['172.16.1.100:8081']

  - job_name: 'Effekta-USV (KCH) Status'
    metrics_path: /ups_metrics
    static_configs:
     - targets: ['10.0.0.104:9199']

  # Service Scrapes via dedicated exporter-container
  - job_name: "PiHole Statistics"
    static_configs:
      - targets: ['172.16.1.20:9100']

  - job_name: "Fritz!Box Statistics"
    static_configs:
      - targets: ['172.16.1.21:9100', '172.16.1.22:9100']

  - job_name: "TeamSpeak 3 Statistics"
    static_configs:
      - targets: ['172.16.1.23:8000']

  - job_name: "NGINX Statistics"
    static_configs:
    - targets: ['172.16.1.24:9113']

  - job_name: "Wireguard Endpoint GEO Locations"
    static_configs:
      - targets: ['172.16.1.25:8000']

  # Internal Monitoring Stack Scrapes
  - job_name: 'Grafana Interal Statistics'
    static_configs:
    - targets: ['172.16.1.10:3000']

  - job_name: 'Prometheus Internal Statistics'
    static_configs:
      - targets: ['172.16.1.12:9090']



#        - job_name: "wireguard-new"
#    static_configs:
#      - targets: ['10.0.0.108:8000']

#  - job_name: 'docker'
#    static_configs:
#      - targets: ['10.0.0.103:19323']
