global:
  scrape_interval:     5s
  external_labels:
    monitor: 'prometheus-scraper'

scrape_configs:
  - job_name: "Node Exporter VM"
    static_configs:
      - targets: ['gameserver0-kch.fink.home:9100', 'storage0-kch.fink.home:9100', 'docker.fink.home:9100', 'github-runner0-kch.fink.home:9100']
  - job_name: "Node Exporter Proxmox"
    static_configs:
      - targets: ['pbs0-kch.fink.home:9100', 'vms1.fink.home:9100', 'vms2.fink.home:9100', 'vms3.fink.home:9100']
  - job_name: "Node Exporter PiHole"
    static_configs:
      - targets: ['pihole0-kch.fink.home:9100', 'pihole1-tg.fink.home:9100']
  - job_name: "Node Exporter External"
    static_configs:
      - targets: ['offsite-backup.fink.vpn:9100']

  - job_name: "PiHole Statistics"
    static_configs:
      - targets: ['172.16.1.20:9100']

  - job_name: "Fritz!Box Statistics"
    static_configs:
      - targets: ['172.16.1.21:9100', '172.16.1.22:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wireguard'
    static_configs:
      - targets: ['10.0.0.102:8000']

  - job_name: "wireguard-new"
    static_configs:
      - targets: ['10.0.0.108:8000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['10.0.0.103:3000']
  
  - job_name: 'usv_effekta'
    metrics_path: /ups_metrics
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.0.104:9199']


  - job_name: 'docker'
    static_configs:
      - targets: ['10.0.0.103:19323']
